services:
  traefik:
    image: traefik:v3.2
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.0
    expose:
      - 80
    command: --config /app/config.cfg
    configs:
      - source: oauth2-proxy-config
        target: /app/config.cfg
    environment:
      OAUTH2_PROXY_UPSTREAMS: http://swagger:8080
    labels:
      traefik.enable: "true"
      traefik.http.routers.oauth.service: "oauth2-proxy"
      traefik.http.routers.oauth.rule: "(Host(`textvault.ru`) && !PathPrefix(`/api`)) || Host(`openapi.bytes2b.ru`)"
      traefik.http.routers.oauth.tls: true
      traefik.http.routers.oauth.tls.certresolver: letsencrypt
      traefik.http.routers.oauth.middlewares: "oauth-signin"

      traefik.http.middlewares.oauth-signin.errors.service: "oauth2-proxy"
      traefik.http.middlewares.oauth-signin.errors.status: "401-403"
      traefik.http.middlewares.oauth-signin.errors.query: "/oauth2/sign_in"
  swagger:
    build:
      context: ../swagger
      target: production-image
    expose:
      - 8080
    labels:
      traefik.enable: "true"
      traefik.http.routers.swagger.rule: "Host(`swagger.textvault.ru`)"
      traefik.http.routers.swagger.tls: true
      traefik.http.routers.swagger.tls.certresolver: letsencrypt

  backend:
    build:
      context: ../backend
      target: backend.Dockerfile
    expose:
      - 8080
    labels:
      traefik.enable: "true"
      traefik.http.routers.backend.rule: "Host(`api.textvault.ru`)"
      traefik.http.routers.backend.tls: true
      traefik.http.routers.backend.tls.certresolver: letsencrypt
    environment:
      CONFIG_PATH: /app/backend/config.yaml
    configs:
      - source: backend-config
        target: /app/backend/config.yaml

  frontend:
    build:
      context: ../frontend
      target: frontend.Dockerfile
    expose:
      - 80
    labels:
      traefik.enable: "true"
      traefik.http.routers.frontend.rule: "Host(`textvault.ru`)"
      traefik.http.routers.frontend.tls: true
      traefik.http.routers.frontend.tls.certresolver: letsencrypt

  migrations:
    build:
      context: ../backend
      target: backend.Dockerfile

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: postgrespwd
    volumes:
      - ./postgres:/var/lib/postgresql/data

  whodb:
    image: clidey/whodb
    expose:
      - 8080
    environment:
      WHODB_POSTGRES: '[{"host":"postgres","user":"postgres","password":"postgrespwd","database":"textvault"}]'

configs:
  oauth-config:
    file: ./configs/oauth2-proxy.cfg
  backend-config:
    file: ./configs/backend.yaml
