// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: paste.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePaste = `-- name: DeletePaste :execrows
DELETE
FROM Pastes
WHERE id = $1
  and author_id = $2
`

type DeletePasteParams struct {
	ID       pgtype.UUID
	AuthorID pgtype.UUID
}

func (q *Queries) DeletePaste(ctx context.Context, arg DeletePasteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePaste, arg.ID, arg.AuthorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPaste = `-- name: GetPaste :one
SELECT id, title, language, author_id, created_at, updated_at
FROM Pastes
WHERE id = $1
`

func (q *Queries) GetPaste(ctx context.Context, id pgtype.UUID) (Paste, error) {
	row := q.db.QueryRow(ctx, getPaste, id)
	var i Paste
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Language,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPastes = `-- name: GetUserPastes :many
SELECT id, title, language, author_id, created_at, updated_at
FROM Pastes
WHERE author_id = $1 LIMIT $2
OFFSET $3
`

type GetUserPastesParams struct {
	AuthorID pgtype.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) GetUserPastes(ctx context.Context, arg GetUserPastesParams) ([]Paste, error) {
	rows, err := q.db.Query(ctx, getUserPastes, arg.AuthorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Paste
	for rows.Next() {
		var i Paste
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Language,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const savePaste = `-- name: SavePaste :one
INSERT INTO Pastes (id, title, language, author_id)
VALUES ($1, $2, $3, $4) RETURNING id, title, language, author_id, created_at, updated_at
`

type SavePasteParams struct {
	ID       pgtype.UUID
	Title    string
	Language string
	AuthorID pgtype.UUID
}

func (q *Queries) SavePaste(ctx context.Context, arg SavePasteParams) (Paste, error) {
	row := q.db.QueryRow(ctx, savePaste,
		arg.ID,
		arg.Title,
		arg.Language,
		arg.AuthorID,
	)
	var i Paste
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Language,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaste = `-- name: UpdatePaste :one
UPDATE Pastes
SET title      = $2,
    language   = $3,
    updated_at = now()
WHERE id = $1
  and author_id = $4 RETURNING id
`

type UpdatePasteParams struct {
	ID       pgtype.UUID
	Title    string
	Language string
	AuthorID pgtype.UUID
}

func (q *Queries) UpdatePaste(ctx context.Context, arg UpdatePasteParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, updatePaste,
		arg.ID,
		arg.Title,
		arg.Language,
		arg.AuthorID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
